# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UK LLC Dataset Documentation
author: UK LLC Data Team
logo: docs/images/GB_full_REG_cropped.png
email: support@ukllc.ac.uk

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - '*freeze*'
  execute_notebooks: force

bibtex_bibfiles:
   - _bibliography/references.bib

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ukllc/jupyter-book  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: Visit our <a href="https://github.com/UKLLC/jupyter-book">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  extra_footer: |
    The UK LLC Guidebook and materials are available publicly under <a href="https://github.com/UKLLC/licencing">open source licenses</a>
  favicon: "docs/images/favicon.ico"  # A path to a favicon image
  google_analytics_id: G-X3F2TFHCXV

parse:
  myst_enable_extensions:
    - html_image

# control footer copywrite
sphinx:
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
    html_show_copyright     : false


